project:
  type: book
  output-dir: _web
  
execute:
  eval: true
  echo: true
  output: false
  freeze: auto  # auto, true, or false

book:
  title: "Hubbard Hall Fundraising Committee"
  subtitle: ""
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - analysis.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: 5
    toc-depth: 5
    toc-expand: false

editor_options:
  chunk_output_type: console
  
# ```{r stop_here, echo=FALSE}
# knitr::knit_exit()
# ```

# ---
# format: html
# editor-options: 
#   chunk-output-type: console
# ---


# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt 
# 