---
format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
---

# Work with the data

## Setup


```{r}
#| label: setup

source(here::here("libraries.R"))

hhdr <- here::here("data-raw")
neon <- fs::path(hhdr, "neon")
judy <- fs::path(hhdr, "judy")
rds <- fs::path(hhdr, "rds")

```


## Get and save data

Accounts data

```{r}
#| label: accounts

acctfname <- "accounts_2025-07-16.csv"

accounts1 <- vroom(
  fs::path(hhdr, acctfname),
  col_types = cols(.default = col_character())
)
glimpse(accounts1)

accounts <- accounts1 |>
  rename_with(.fn = tolower) |>
  rename(
    name = account,
    accountid = id,
    subtype = 4,
    pcontact = `primary contact`,
    zip = `zip code`,
    created = `created on`,
    ocategory = `origin category`,
    odetail = `origin detail`
  ) |>
  select(-...20)
skimr::skim(accounts)

saveRDS(accounts, fs::path(rds, "accounts.rds"))

```

Households data

```{r}
#| label: households

hhfname <- "households_2025-07-16.csv"

hh1 <- vroom(
  fs::path(hhdr, hhfname),
  col_types = cols(.default = col_character())
)
skim(hh1)
glimpse(hh1)

hh2 <- hh1 |>
  rename_with(.fn = tolower) |>
  select(
    hhname = 1,
    hhcontact = 2,
    hhaccountid = 3,
    hhemail = email,
    hhphone = 5,
    hhwebsite = website,
    address,
    city,
    state,
    zip = `zip code`,
    country,
    hhsalutation = `household salutation`,
    hhncontacts = `household contacts`,
    totrevenue = `total revenue`,
    ntransactions = `number of transactions`,
    updated = `last updated`,
    createdon = `created on`
  )
cbind(names(hh1), names(hh2))
glimpse(hh2)

hh3 <- hh2 |>
  mutate(
    hhncontacts = as.integer(hhncontacts),
    totrevenue = as.numeric(totrevenue),
    ntransactions = as.integer(ntransactions),
    updated = lubridate::mdy_hms(updated) |> as.Date(),
    createdon = lubridate::mdy_hms(createdon) |> as.Date()
  )

skimr::skim(hh3)
glimpse(hh3)

saveRDS(hh3, fs::path(rds, "households.rds"))

```

### Link household members based on address (?).

```{r}
accounts <- readRDS(fs::path(rds, "accounts.rds"))
hholds <- readRDS(fs::path(rds, "households.rds"))

glimpse(accounts)
glimpse(hholds)

mrg1 <- left_join(
  hholds,
  accounts,
  by = join_by(address, city, state, zip, country),
  relationship = "many-to-many"
) |>
  mutate(nrecs = n(), .by = c(address, city, state, zip, country))

tmp <- mrg1 |>
  select(hhaccountid, accountid, nrecs, hhncontacts, everything()) |>
  arrange(country, zip, state, city, address)


```



## Analysis

```{r}

accounts <- readRDS(fs::path(rds, "accounts.rds"))

```


## Explore


```{r}

fname <- "accounts_2025-07-16.csv"

df1 <- vroom(
  fs::path(hhdr, fname),
  col_types = cols(.default = col_character())
)

accounts <- df1 |>
  rename_with(.fn = tolower) |>
  rename(
    subtype = 4,
    pcontact = `primary contact`,
    zip = `zip code`,
    created = `created on`,
    ocategory = `origin category`,
    odetail = `origin detail`
  ) |>
  select(-...20)
skimr::skim(accounts)

count(accounts, type)

count(accounts, type, subtype) |>
  arrange(type, desc(n))

# not much value in these groups
count(accounts, state, sort = TRUE) |> mutate(pct = n / sum(n))
count(accounts, source, sort = TRUE) |> mutate(pct = n / sum(n))
count(accounts, ocategory, sort = TRUE) |> mutate(pct = n / sum(n))
count(accounts, odetail, sort = TRUE) |> mutate(pct = n / sum(n))

```



```{r}

fname <- "donations_2025-07-16.csv"

donors1 <- vroom(
  fs::path(hhdr, fname),
  col_types = cols(.default = col_character())
)
skimr::skim(donors1)
glimpse(donors1)

donors2 <- donors1 |>
  rename_with(.fn = tolower) |>
  rename(
    name = 1,
    accountid = 2,
    date = `donated on`,
    sysupdate = `system updates`,
    sysmessages = `system messages`
  ) |>
  select(-...15) |>
  mutate(amount1 = as.numeric(amount), date = lubridate::mdy(date))

skimr::skim(donors2)

donors3 <- donors2 |>
  select(-amount) |>
  rename(amount = amount1)

```


```{r}
donors4 <- donors3 |>
  summarise(amount = sum(amount), .by = c(accountid, name)) |>
  arrange(desc(amount)) |>
  left_join(
    accounts |> select(accountid = id, accountname = account, type),
    by = join_by(accountid)
  )

donors4


keep <- "Roome"
keep <- "Estey"

donors3 |>
  filter(str_detect(name, keep)) |>
  select(name, accountid, type, date, campaign, notes, amount) |>
  # arrange(desc(amount)) |>
  arrange(date) |>
  mutate(rollsum = cumsum(amount))

# donors2 |>
#   filter(str_detect(name, keep)) |>
#   mutate()
# select(name, accountid, type, date, campaign, notes, amount) |>
#   arrange(desc(amount)) |>
#   mutate(rollsum = cumsum(amount))

```