---
editor_options:
  chunk_output_type: console
---

# Notes to self

## TODO:

## About the Neon data

Main data we currently have access to:

-   Accounts
    - identifying info on every "account" (Individual or Company) who's had contact with Hubbard Hall through donations, attending performances, or participating in classes
    - includes people who have died, moved out of the area, or lost all interest in HH so needs to be filtered
    - Judy fills out fields for "deceased" and "do not contact" which allows filtering
    - fields include id #; type (Individual or Company); primary person's address, email & phone; when record created

-  Households
    - defines 

## Neon support links

-   [Dashboard](https://hubbardhall.app.neoncrm.com/np/admin/content/contentList.do)

-   [Reporting](https://support.neonone.com/hc/en-us/sections/4407397872013-Reporting)
-   [Soft credits](https://support.neonone.com/hc/en-us/articles/10163196415373-Identify-Transactions-That-Have-Soft-Credits-Applied)
<!-- -   []()
-   []()
-   []() -->

## Linking households and individuals

-   Create new Communication and Mailing Report, subtype Additional Contact Report -- has all contacts, in separate rows
    -   Add all address info
    -   All account ids
    -   Requires criteria to run, so select expansive criteria -- I chose Main account is not blank